require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewtasksController do

  # This should return the minimal set of attributes required to create a valid
  # Newtask. As you add validations to Newtask, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all newtasks as @newtasks" do
      newtask = Newtask.create! valid_attributes
      get :index
      assigns(:newtasks).should eq([newtask])
    end
  end

  describe "GET show" do
    it "assigns the requested newtask as @newtask" do
      newtask = Newtask.create! valid_attributes
      get :show, :id => newtask.id.to_s
      assigns(:newtask).should eq(newtask)
    end
  end

  describe "GET new" do
    it "assigns a new newtask as @newtask" do
      get :new
      assigns(:newtask).should be_a_new(Newtask)
    end
  end

  describe "GET edit" do
    it "assigns the requested newtask as @newtask" do
      newtask = Newtask.create! valid_attributes
      get :edit, :id => newtask.id.to_s
      assigns(:newtask).should eq(newtask)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Newtask" do
        expect {
          post :create, :newtask => valid_attributes
        }.to change(Newtask, :count).by(1)
      end

      it "assigns a newly created newtask as @newtask" do
        post :create, :newtask => valid_attributes
        assigns(:newtask).should be_a(Newtask)
        assigns(:newtask).should be_persisted
      end

      it "redirects to the created newtask" do
        post :create, :newtask => valid_attributes
        response.should redirect_to(Newtask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved newtask as @newtask" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newtask.any_instance.stub(:save).and_return(false)
        post :create, :newtask => {}
        assigns(:newtask).should be_a_new(Newtask)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newtask.any_instance.stub(:save).and_return(false)
        post :create, :newtask => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested newtask" do
        newtask = Newtask.create! valid_attributes
        # Assuming there are no other newtasks in the database, this
        # specifies that the Newtask created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Newtask.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => newtask.id, :newtask => {'these' => 'params'}
      end

      it "assigns the requested newtask as @newtask" do
        newtask = Newtask.create! valid_attributes
        put :update, :id => newtask.id, :newtask => valid_attributes
        assigns(:newtask).should eq(newtask)
      end

      it "redirects to the newtask" do
        newtask = Newtask.create! valid_attributes
        put :update, :id => newtask.id, :newtask => valid_attributes
        response.should redirect_to(newtask)
      end
    end

    describe "with invalid params" do
      it "assigns the newtask as @newtask" do
        newtask = Newtask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newtask.any_instance.stub(:save).and_return(false)
        put :update, :id => newtask.id.to_s, :newtask => {}
        assigns(:newtask).should eq(newtask)
      end

      it "re-renders the 'edit' template" do
        newtask = Newtask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newtask.any_instance.stub(:save).and_return(false)
        put :update, :id => newtask.id.to_s, :newtask => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested newtask" do
      newtask = Newtask.create! valid_attributes
      expect {
        delete :destroy, :id => newtask.id.to_s
      }.to change(Newtask, :count).by(-1)
    end

    it "redirects to the newtasks list" do
      newtask = Newtask.create! valid_attributes
      delete :destroy, :id => newtask.id.to_s
      response.should redirect_to(newtasks_url)
    end
  end

end
